### ISSUE TITLE
License compatibility

### ISSUE THREAD

**Issue by val-ms** [icebergdefender/rust-clamav#21]
I see that this project is licensed under MIT.
libclamav is licensed under GPLv2.  Unlike with LGPL licenses, GPL licenses are copyleft even if you dynamically link.  

If this crate is used within other projects and then linked with libclamav, the GPLv2 license will apply to those projects as well.

I would recommend changing the license for this project to GPLv2 to match.

**Comment by zsims** [comment]
Hey, sorry for the long delay.

Good catch, I'll update the license.
